[package]
name = "qubit-redact-serde-disabled-fixture"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
qubit-redact = {
    path = "../../../../../rs-redact",
    version = "0.4",
    default-features = false,
}
qubit-redact-derive = { path = "../../../.." }
serde = "1"
